/* Auto-generated by scripts/curate-catalog.mjs — do not edit by hand */
export type CatalogCategoryId =
  | "living"
  | "corner"
  | "bedset"
  | "alacati"
  | "alisya-gold"
  | "alyans"
  | "tokyo"
  | "others";

export type CatalogItem = {
  id: string;
  title: string;
  categoryId: CatalogCategoryId;
  collection: string | null;
  imageUrl: string;
  imageUrls: string[];
};

export const catalogYear = 2027;

export const catalogItems: CatalogItem[] = [
  {
    "id": "AW-2027-001",
    "title": "Opulento",
    "categoryId": "living",
    "collection": "Opulento",
    "imageUrl": "/catalog/2027/living/opulento.webp",
    "imageUrls": [
      "/catalog/2027/living/opulento.webp"
    ]
  },
  {
    "id": "AW-2027-002",
    "title": "İmperial",
    "categoryId": "living",
    "collection": "İmperial",
    "imageUrl": "/catalog/2027/living/imperial-01.webp",
    "imageUrls": [
      "/catalog/2027/living/imperial-01.webp",
      "/catalog/2027/living/imperial-02.webp"
    ]
  },
  {
    "id": "AW-2027-003",
    "title": "Sontuoso",
    "categoryId": "living",
    "collection": "Sontuoso",
    "imageUrl": "/catalog/2027/living/sontuoso-01.webp",
    "imageUrls": [
      "/catalog/2027/living/sontuoso-01.webp",
      "/catalog/2027/living/sontuoso-02.webp"
    ]
  },
  {
    "id": "AW-2027-004",
    "title": "İncanto",
    "categoryId": "living",
    "collection": "İncanto",
    "imageUrl": "/catalog/2027/living/incanto-01.webp",
    "imageUrls": [
      "/catalog/2027/living/incanto-01.webp",
      "/catalog/2027/living/incanto-02.webp"
    ]
  },
  {
    "id": "AW-2027-005",
    "title": "Setoso",
    "categoryId": "living",
    "collection": "Setoso",
    "imageUrl": "/catalog/2027/living/setoso-01.webp",
    "imageUrls": [
      "/catalog/2027/living/setoso-01.webp",
      "/catalog/2027/living/setoso-02.webp"
    ]
  },
  {
    "id": "AW-2027-006",
    "title": "Lusso",
    "categoryId": "living",
    "collection": "Lusso",
    "imageUrl": "/catalog/2027/living/lusso-01.webp",
    "imageUrls": [
      "/catalog/2027/living/lusso-01.webp",
      "/catalog/2027/living/lusso-02.webp"
    ]
  },
  {
    "id": "AW-2027-007",
    "title": "Dore",
    "categoryId": "living",
    "collection": "Dore",
    "imageUrl": "/catalog/2027/living/dore.webp",
    "imageUrls": [
      "/catalog/2027/living/dore.webp"
    ]
  },
  {
    "id": "AW-2027-008",
    "title": "Aria",
    "categoryId": "living",
    "collection": "Aria",
    "imageUrl": "/catalog/2027/living/aria.webp",
    "imageUrls": [
      "/catalog/2027/living/aria.webp"
    ]
  },
  {
    "id": "AW-2027-009",
    "title": "Nobile",
    "categoryId": "living",
    "collection": "Nobile",
    "imageUrl": "/catalog/2027/living/nobile.webp",
    "imageUrls": [
      "/catalog/2027/living/nobile.webp"
    ]
  },
  {
    "id": "AW-2027-010",
    "title": "Sogna",
    "categoryId": "living",
    "collection": "Sogna",
    "imageUrl": "/catalog/2027/living/sogna-01.webp",
    "imageUrls": [
      "/catalog/2027/living/sogna-01.webp",
      "/catalog/2027/living/sogna-02.webp"
    ]
  },
  {
    "id": "AW-2027-011",
    "title": "Elegante",
    "categoryId": "living",
    "collection": "Elegante",
    "imageUrl": "/catalog/2027/living/elegante.webp",
    "imageUrls": [
      "/catalog/2027/living/elegante.webp"
    ]
  },
  {
    "id": "AW-2027-012",
    "title": "Armonioso",
    "categoryId": "living",
    "collection": "Armonioso",
    "imageUrl": "/catalog/2027/living/armonioso-01.webp",
    "imageUrls": [
      "/catalog/2027/living/armonioso-01.webp",
      "/catalog/2027/living/armonioso-02.webp"
    ]
  },
  {
    "id": "AW-2027-013",
    "title": "Legno",
    "categoryId": "living",
    "collection": "Legno",
    "imageUrl": "/catalog/2027/living/legno.webp",
    "imageUrls": [
      "/catalog/2027/living/legno.webp"
    ]
  },
  {
    "id": "AW-2027-014",
    "title": "Dolcezza",
    "categoryId": "corner",
    "collection": "Dolcezza",
    "imageUrl": "/catalog/2027/corner/dolcezza.webp",
    "imageUrls": [
      "/catalog/2027/corner/dolcezza.webp"
    ]
  },
  {
    "id": "AW-2027-015",
    "title": "Sofia",
    "categoryId": "corner",
    "collection": "Sofia",
    "imageUrl": "/catalog/2027/corner/sofia.webp",
    "imageUrls": [
      "/catalog/2027/corner/sofia.webp"
    ]
  },
  {
    "id": "AW-2027-016",
    "title": "Tesoro",
    "categoryId": "corner",
    "collection": "Tesoro",
    "imageUrl": "/catalog/2027/corner/tesoro.webp",
    "imageUrls": [
      "/catalog/2027/corner/tesoro.webp"
    ]
  },
  {
    "id": "AW-2027-017",
    "title": "Avonnis",
    "categoryId": "bedset",
    "collection": "Avonnis",
    "imageUrl": "/catalog/2027/bedset/avonnis-01.webp",
    "imageUrls": [
      "/catalog/2027/bedset/avonnis-01.webp",
      "/catalog/2027/bedset/avonnis-02.webp",
      "/catalog/2027/bedset/avonnis-03.webp",
      "/catalog/2027/bedset/avonnis-04.webp",
      "/catalog/2027/bedset/avonnis-05.webp"
    ]
  },
  {
    "id": "AW-2027-018",
    "title": "Hayal",
    "categoryId": "bedset",
    "collection": "Hayal",
    "imageUrl": "/catalog/2027/bedset/hayal.webp",
    "imageUrls": [
      "/catalog/2027/bedset/hayal.webp"
    ]
  },
  {
    "id": "AW-2027-019",
    "title": "Venüs",
    "categoryId": "bedset",
    "collection": "Venüs",
    "imageUrl": "/catalog/2027/bedset/venus-01.webp",
    "imageUrls": [
      "/catalog/2027/bedset/venus-01.webp",
      "/catalog/2027/bedset/venus-02.webp"
    ]
  },
  {
    "id": "AW-2027-020",
    "title": "Efsane",
    "categoryId": "bedset",
    "collection": "Efsane",
    "imageUrl": "/catalog/2027/bedset/efsane.webp",
    "imageUrls": [
      "/catalog/2027/bedset/efsane.webp"
    ]
  },
  {
    "id": "AW-2027-021",
    "title": "Carmen",
    "categoryId": "bedset",
    "collection": "Carmen",
    "imageUrl": "/catalog/2027/bedset/carmen-01.webp",
    "imageUrls": [
      "/catalog/2027/bedset/carmen-01.webp",
      "/catalog/2027/bedset/carmen-02.webp",
      "/catalog/2027/bedset/carmen-03.webp"
    ]
  },
  {
    "id": "AW-2027-022",
    "title": "Rüzgar",
    "categoryId": "bedset",
    "collection": "Rüzgar",
    "imageUrl": "/catalog/2027/bedset/ruzgar.webp",
    "imageUrls": [
      "/catalog/2027/bedset/ruzgar.webp"
    ]
  },
  {
    "id": "AW-2027-023",
    "title": "Rahat",
    "categoryId": "bedset",
    "collection": "Rahat",
    "imageUrl": "/catalog/2027/bedset/rahat.webp",
    "imageUrls": [
      "/catalog/2027/bedset/rahat.webp"
    ]
  },
  {
    "id": "AW-2027-024",
    "title": "Luxury",
    "categoryId": "bedset",
    "collection": "Luxury",
    "imageUrl": "/catalog/2027/bedset/luxury-01.webp",
    "imageUrls": [
      "/catalog/2027/bedset/luxury-01.webp",
      "/catalog/2027/bedset/luxury-02.webp",
      "/catalog/2027/bedset/luxury-03.webp",
      "/catalog/2027/bedset/luxury-04.webp"
    ]
  },
  {
    "id": "AW-2027-025",
    "title": "Bella",
    "categoryId": "bedset",
    "collection": "Bella",
    "imageUrl": "/catalog/2027/bedset/bella.webp",
    "imageUrls": [
      "/catalog/2027/bedset/bella.webp"
    ]
  },
  {
    "id": "AW-2027-026",
    "title": "Meram",
    "categoryId": "bedset",
    "collection": "Meram",
    "imageUrl": "/catalog/2027/bedset/meram-01.webp",
    "imageUrls": [
      "/catalog/2027/bedset/meram-01.webp",
      "/catalog/2027/bedset/meram-02.webp"
    ]
  },
  {
    "id": "AW-2027-027",
    "title": "Tesla",
    "categoryId": "bedset",
    "collection": "Tesla",
    "imageUrl": "/catalog/2027/bedset/tesla-01.webp",
    "imageUrls": [
      "/catalog/2027/bedset/tesla-01.webp",
      "/catalog/2027/bedset/tesla-02.webp"
    ]
  },
  {
    "id": "AW-2027-028",
    "title": "Nirvana",
    "categoryId": "bedset",
    "collection": "Nirvana",
    "imageUrl": "/catalog/2027/bedset/nirvana-01.webp",
    "imageUrls": [
      "/catalog/2027/bedset/nirvana-01.webp",
      "/catalog/2027/bedset/nirvana-02.webp",
      "/catalog/2027/bedset/nirvana-03.webp",
      "/catalog/2027/bedset/nirvana-04.webp"
    ]
  },
  {
    "id": "AW-2027-029",
    "title": "Alaçatı Yatak Odası",
    "categoryId": "alacati",
    "collection": "Alaçatı Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alacati-yatak-odasi-01.webp",
    "imageUrls": [
      "/catalog/2027/bedroom/alacati-yatak-odasi-01.webp",
      "/catalog/2027/bedroom/alacati-yatak-odasi-02.webp",
      "/catalog/2027/bedroom/alacati-yatak-odasi-03.webp",
      "/catalog/2027/bedroom/alacati-yatak-odasi-04.webp",
      "/catalog/2027/bedroom/alacati-yatak-odasi-05.webp"
    ]
  },
  {
    "id": "AW-2027-030",
    "title": "Alaçatı Yemek Odası",
    "categoryId": "alacati",
    "collection": "Alaçatı Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alacati-yemek-odasi-01.webp",
    "imageUrls": [
      "/catalog/2027/dining/alacati-yemek-odasi-01.webp",
      "/catalog/2027/dining/alacati-yemek-odasi-02.webp",
      "/catalog/2027/dining/alacati-yemek-odasi-03.webp",
      "/catalog/2027/dining/alacati-yemek-odasi-04.webp",
      "/catalog/2027/dining/alacati-yemek-odasi-05.webp"
    ]
  },
  {
    "id": "AW-2027-031",
    "title": "Alisya Gold Yatak Odası",
    "categoryId": "alisya-gold",
    "collection": "Alisya Gold Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alisya-gold-yatak-odasi-01.webp",
    "imageUrls": [
      "/catalog/2027/bedroom/alisya-gold-yatak-odasi-01.webp",
      "/catalog/2027/bedroom/alisya-gold-yatak-odasi-02.webp",
      "/catalog/2027/bedroom/alisya-gold-yatak-odasi-03.webp",
      "/catalog/2027/bedroom/alisya-gold-yatak-odasi-04.webp",
      "/catalog/2027/bedroom/alisya-gold-yatak-odasi-05.webp"
    ]
  },
  {
    "id": "AW-2027-032",
    "title": "Alisya Gold Yemek Odası",
    "categoryId": "alisya-gold",
    "collection": "Alisya Gold Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alisya-gold-yemek-odasi-01.webp",
    "imageUrls": [
      "/catalog/2027/dining/alisya-gold-yemek-odasi-01.webp",
      "/catalog/2027/dining/alisya-gold-yemek-odasi-02.webp",
      "/catalog/2027/dining/alisya-gold-yemek-odasi-03.webp",
      "/catalog/2027/dining/alisya-gold-yemek-odasi-04.webp"
    ]
  },
  {
    "id": "AW-2027-033",
    "title": "Alyans Yatak Odası",
    "categoryId": "alyans",
    "collection": "Alyans Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alyans-yatak-odasi-01.webp",
    "imageUrls": [
      "/catalog/2027/bedroom/alyans-yatak-odasi-01.webp",
      "/catalog/2027/bedroom/alyans-yatak-odasi-02.webp",
      "/catalog/2027/bedroom/alyans-yatak-odasi-03.webp",
      "/catalog/2027/bedroom/alyans-yatak-odasi-04.webp",
      "/catalog/2027/bedroom/alyans-yatak-odasi-05.webp"
    ]
  },
  {
    "id": "AW-2027-034",
    "title": "Alyans Yemek Odası",
    "categoryId": "alyans",
    "collection": "Alyans Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alyans-yemek-odasi-01.webp",
    "imageUrls": [
      "/catalog/2027/dining/alyans-yemek-odasi-01.webp",
      "/catalog/2027/dining/alyans-yemek-odasi-02.webp",
      "/catalog/2027/dining/alyans-yemek-odasi-03.webp",
      "/catalog/2027/dining/alyans-yemek-odasi-04.webp"
    ]
  },
  {
    "id": "AW-2027-035",
    "title": "Tokyo Yatak Odası",
    "categoryId": "tokyo",
    "collection": "Tokyo Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/tokyo-yatak-odasi-01.webp",
    "imageUrls": [
      "/catalog/2027/bedroom/tokyo-yatak-odasi-01.webp",
      "/catalog/2027/bedroom/tokyo-yatak-odasi-02.webp",
      "/catalog/2027/bedroom/tokyo-yatak-odasi-03.webp",
      "/catalog/2027/bedroom/tokyo-yatak-odasi-04.webp",
      "/catalog/2027/bedroom/tokyo-yatak-odasi-05.webp",
      "/catalog/2027/bedroom/tokyo-yatak-odasi-06.webp"
    ]
  },
  {
    "id": "AW-2027-036",
    "title": "Tokyo Yemek Odası",
    "categoryId": "tokyo",
    "collection": "Tokyo Yemek Odası",
    "imageUrl": "/catalog/2027/dining/tokyo-yemek-odasi-01.webp",
    "imageUrls": [
      "/catalog/2027/dining/tokyo-yemek-odasi-01.webp",
      "/catalog/2027/dining/tokyo-yemek-odasi-02.webp",
      "/catalog/2027/dining/tokyo-yemek-odasi-03.webp",
      "/catalog/2027/dining/tokyo-yemek-odasi-04.webp"
    ]
  }
];
