/* Auto-generated by scripts/import-catalog.mjs — do not edit by hand */
export type CatalogCategoryId =
  | "living"
  | "bedroom"
  | "bedset"
  | "dining"
  | "lamia"
  | "others";

export type CatalogItem = {
  id: string;
  title: string;
  categoryId: CatalogCategoryId;
  collection: string | null;
  imageUrl: string;
};

export const catalogYear = 2027;

export const catalogItems: CatalogItem[] = [
  {
    "id": "AW-2027-001",
    "title": "Salon & Oturma — 001",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-001.webp"
  },
  {
    "id": "AW-2027-002",
    "title": "Salon & Oturma — 002",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-002.webp"
  },
  {
    "id": "AW-2027-003",
    "title": "Salon & Oturma — 003",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-003.webp"
  },
  {
    "id": "AW-2027-004",
    "title": "Salon & Oturma — 004",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-004.webp"
  },
  {
    "id": "AW-2027-005",
    "title": "Salon & Oturma — 005",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-005.webp"
  },
  {
    "id": "AW-2027-006",
    "title": "Salon & Oturma — 006",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-006.webp"
  },
  {
    "id": "AW-2027-007",
    "title": "Salon & Oturma — 007",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-007.webp"
  },
  {
    "id": "AW-2027-008",
    "title": "Salon & Oturma — 008",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-008.webp"
  },
  {
    "id": "AW-2027-009",
    "title": "Salon & Oturma — 009",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-009.webp"
  },
  {
    "id": "AW-2027-010",
    "title": "Salon & Oturma — 010",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-010.webp"
  },
  {
    "id": "AW-2027-011",
    "title": "Salon & Oturma — 011",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-011.webp"
  },
  {
    "id": "AW-2027-012",
    "title": "Salon & Oturma — 012",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-012.webp"
  },
  {
    "id": "AW-2027-013",
    "title": "Salon & Oturma — 013",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-013.webp"
  },
  {
    "id": "AW-2027-014",
    "title": "Salon & Oturma — 014",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-014.webp"
  },
  {
    "id": "AW-2027-015",
    "title": "Salon & Oturma — 015",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-015.webp"
  },
  {
    "id": "AW-2027-016",
    "title": "Salon & Oturma — 016",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-016.webp"
  },
  {
    "id": "AW-2027-017",
    "title": "Salon & Oturma — 017",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-017.webp"
  },
  {
    "id": "AW-2027-018",
    "title": "Salon & Oturma — 018",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-018.webp"
  },
  {
    "id": "AW-2027-019",
    "title": "Salon & Oturma — 019",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-019.webp"
  },
  {
    "id": "AW-2027-020",
    "title": "Salon & Oturma — 020",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-020.webp"
  },
  {
    "id": "AW-2027-021",
    "title": "Salon & Oturma — 021",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-021.webp"
  },
  {
    "id": "AW-2027-022",
    "title": "Salon & Oturma — 022",
    "categoryId": "living",
    "collection": "Salon & Oturma",
    "imageUrl": "/catalog/2027/living/salon-oturma-022.webp"
  },
  {
    "id": "AW-2027-023",
    "title": "Lamia — 023",
    "categoryId": "lamia",
    "collection": "Lamia",
    "imageUrl": "/catalog/2027/lamia/lamia-023.webp"
  },
  {
    "id": "AW-2027-024",
    "title": "Lamia — 024",
    "categoryId": "lamia",
    "collection": "Lamia",
    "imageUrl": "/catalog/2027/lamia/lamia-024.webp"
  },
  {
    "id": "AW-2027-025",
    "title": "Lamia — 025",
    "categoryId": "lamia",
    "collection": "Lamia",
    "imageUrl": "/catalog/2027/lamia/lamia-025.webp"
  },
  {
    "id": "AW-2027-026",
    "title": "Lamia — 026",
    "categoryId": "lamia",
    "collection": "Lamia",
    "imageUrl": "/catalog/2027/lamia/lamia-026.webp"
  },
  {
    "id": "AW-2027-027",
    "title": "Yatak & Baza — 027",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-027.webp"
  },
  {
    "id": "AW-2027-028",
    "title": "Yatak & Baza — 028",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-028.webp"
  },
  {
    "id": "AW-2027-029",
    "title": "Yatak & Baza — 029",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-029.webp"
  },
  {
    "id": "AW-2027-030",
    "title": "Yatak & Baza — 030",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-030.webp"
  },
  {
    "id": "AW-2027-031",
    "title": "Yatak & Baza — 031",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-031.webp"
  },
  {
    "id": "AW-2027-032",
    "title": "Yatak & Baza — 032",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-032.webp"
  },
  {
    "id": "AW-2027-033",
    "title": "Yatak & Baza — 033",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-033.webp"
  },
  {
    "id": "AW-2027-034",
    "title": "Yatak & Baza — 034",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-034.webp"
  },
  {
    "id": "AW-2027-035",
    "title": "Yatak & Baza — 035",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-035.webp"
  },
  {
    "id": "AW-2027-036",
    "title": "Yatak & Baza — 036",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-036.webp"
  },
  {
    "id": "AW-2027-037",
    "title": "Yatak & Baza — 037",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-037.webp"
  },
  {
    "id": "AW-2027-038",
    "title": "Yatak & Baza — 038",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-038.webp"
  },
  {
    "id": "AW-2027-039",
    "title": "Yatak & Baza — 039",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-039.webp"
  },
  {
    "id": "AW-2027-040",
    "title": "Yatak & Baza — 040",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-040.webp"
  },
  {
    "id": "AW-2027-041",
    "title": "Yatak & Baza — 041",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-041.webp"
  },
  {
    "id": "AW-2027-042",
    "title": "Yatak & Baza — 042",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-042.webp"
  },
  {
    "id": "AW-2027-043",
    "title": "Yatak & Baza — 043",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-043.webp"
  },
  {
    "id": "AW-2027-044",
    "title": "Yatak & Baza — 044",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-044.webp"
  },
  {
    "id": "AW-2027-045",
    "title": "Yatak & Baza — 045",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-045.webp"
  },
  {
    "id": "AW-2027-046",
    "title": "Yatak & Baza — 046",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-046.webp"
  },
  {
    "id": "AW-2027-047",
    "title": "Yatak & Baza — 047",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-047.webp"
  },
  {
    "id": "AW-2027-048",
    "title": "Yatak & Baza — 048",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-048.webp"
  },
  {
    "id": "AW-2027-049",
    "title": "Yatak & Baza — 049",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-049.webp"
  },
  {
    "id": "AW-2027-050",
    "title": "Yatak & Baza — 050",
    "categoryId": "bedset",
    "collection": "Yatak & Baza",
    "imageUrl": "/catalog/2027/bedset/yatak-baza-050.webp"
  },
  {
    "id": "AW-2027-051",
    "title": "Alaçatı Yatak Odası — 051",
    "categoryId": "bedroom",
    "collection": "Alaçatı Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alacati-yatak-odasi-051.webp"
  },
  {
    "id": "AW-2027-052",
    "title": "Alaçatı Yatak Odası — 052",
    "categoryId": "bedroom",
    "collection": "Alaçatı Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alacati-yatak-odasi-052.webp"
  },
  {
    "id": "AW-2027-053",
    "title": "Alaçatı Yatak Odası — 053",
    "categoryId": "bedroom",
    "collection": "Alaçatı Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alacati-yatak-odasi-053.webp"
  },
  {
    "id": "AW-2027-054",
    "title": "Alaçatı Yatak Odası — 054",
    "categoryId": "bedroom",
    "collection": "Alaçatı Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alacati-yatak-odasi-054.webp"
  },
  {
    "id": "AW-2027-055",
    "title": "Alaçatı Yatak Odası — 055",
    "categoryId": "bedroom",
    "collection": "Alaçatı Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alacati-yatak-odasi-055.webp"
  },
  {
    "id": "AW-2027-056",
    "title": "Alaçatı Yemek Odası — 056",
    "categoryId": "dining",
    "collection": "Alaçatı Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alacati-yemek-odasi-056.webp"
  },
  {
    "id": "AW-2027-057",
    "title": "Alaçatı Yemek Odası — 057",
    "categoryId": "dining",
    "collection": "Alaçatı Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alacati-yemek-odasi-057.webp"
  },
  {
    "id": "AW-2027-058",
    "title": "Alaçatı Yemek Odası — 058",
    "categoryId": "dining",
    "collection": "Alaçatı Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alacati-yemek-odasi-058.webp"
  },
  {
    "id": "AW-2027-059",
    "title": "Alaçatı Yemek Odası — 059",
    "categoryId": "dining",
    "collection": "Alaçatı Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alacati-yemek-odasi-059.webp"
  },
  {
    "id": "AW-2027-060",
    "title": "Alaçatı Yemek Odası — 060",
    "categoryId": "dining",
    "collection": "Alaçatı Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alacati-yemek-odasi-060.webp"
  },
  {
    "id": "AW-2027-061",
    "title": "Alisya Gold Yatak Odası — 061",
    "categoryId": "bedroom",
    "collection": "Alisya Gold Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alisya-gold-yatak-odasi-061.webp"
  },
  {
    "id": "AW-2027-062",
    "title": "Alisya Gold Yatak Odası — 062",
    "categoryId": "bedroom",
    "collection": "Alisya Gold Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alisya-gold-yatak-odasi-062.webp"
  },
  {
    "id": "AW-2027-063",
    "title": "Alisya Gold Yatak Odası — 063",
    "categoryId": "bedroom",
    "collection": "Alisya Gold Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alisya-gold-yatak-odasi-063.webp"
  },
  {
    "id": "AW-2027-064",
    "title": "Alisya Gold Yatak Odası — 064",
    "categoryId": "bedroom",
    "collection": "Alisya Gold Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alisya-gold-yatak-odasi-064.webp"
  },
  {
    "id": "AW-2027-065",
    "title": "Alisya Gold Yatak Odası — 065",
    "categoryId": "bedroom",
    "collection": "Alisya Gold Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alisya-gold-yatak-odasi-065.webp"
  },
  {
    "id": "AW-2027-066",
    "title": "Alisya Gold Yemek Odası — 066",
    "categoryId": "dining",
    "collection": "Alisya Gold Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alisya-gold-yemek-odasi-066.webp"
  },
  {
    "id": "AW-2027-067",
    "title": "Alisya Gold Yemek Odası — 067",
    "categoryId": "dining",
    "collection": "Alisya Gold Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alisya-gold-yemek-odasi-067.webp"
  },
  {
    "id": "AW-2027-068",
    "title": "Alisya Gold Yemek Odası — 068",
    "categoryId": "dining",
    "collection": "Alisya Gold Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alisya-gold-yemek-odasi-068.webp"
  },
  {
    "id": "AW-2027-069",
    "title": "Alisya Gold Yemek Odası — 069",
    "categoryId": "dining",
    "collection": "Alisya Gold Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alisya-gold-yemek-odasi-069.webp"
  },
  {
    "id": "AW-2027-070",
    "title": "Alyans Yatak Odası — 070",
    "categoryId": "bedroom",
    "collection": "Alyans Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alyans-yatak-odasi-070.webp"
  },
  {
    "id": "AW-2027-071",
    "title": "Alyans Yatak Odası — 071",
    "categoryId": "bedroom",
    "collection": "Alyans Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alyans-yatak-odasi-071.webp"
  },
  {
    "id": "AW-2027-072",
    "title": "Alyans Yatak Odası — 072",
    "categoryId": "bedroom",
    "collection": "Alyans Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alyans-yatak-odasi-072.webp"
  },
  {
    "id": "AW-2027-073",
    "title": "Alyans Yatak Odası — 073",
    "categoryId": "bedroom",
    "collection": "Alyans Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alyans-yatak-odasi-073.webp"
  },
  {
    "id": "AW-2027-074",
    "title": "Alyans Yatak Odası — 074",
    "categoryId": "bedroom",
    "collection": "Alyans Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/alyans-yatak-odasi-074.webp"
  },
  {
    "id": "AW-2027-075",
    "title": "Alyans Yemek Odası — 075",
    "categoryId": "dining",
    "collection": "Alyans Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alyans-yemek-odasi-075.webp"
  },
  {
    "id": "AW-2027-076",
    "title": "Alyans Yemek Odası — 076",
    "categoryId": "dining",
    "collection": "Alyans Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alyans-yemek-odasi-076.webp"
  },
  {
    "id": "AW-2027-077",
    "title": "Alyans Yemek Odası — 077",
    "categoryId": "dining",
    "collection": "Alyans Yemek Odası",
    "imageUrl": "/catalog/2027/dining/alyans-yemek-odasi-077.webp"
  },
  {
    "id": "AW-2027-078",
    "title": "Tokyo Yatak Odası — 078",
    "categoryId": "bedroom",
    "collection": "Tokyo Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/tokyo-yatak-odasi-078.webp"
  },
  {
    "id": "AW-2027-079",
    "title": "Tokyo Yatak Odası — 079",
    "categoryId": "bedroom",
    "collection": "Tokyo Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/tokyo-yatak-odasi-079.webp"
  },
  {
    "id": "AW-2027-080",
    "title": "Tokyo Yatak Odası — 080",
    "categoryId": "bedroom",
    "collection": "Tokyo Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/tokyo-yatak-odasi-080.webp"
  },
  {
    "id": "AW-2027-081",
    "title": "Tokyo Yatak Odası — 081",
    "categoryId": "bedroom",
    "collection": "Tokyo Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/tokyo-yatak-odasi-081.webp"
  },
  {
    "id": "AW-2027-082",
    "title": "Tokyo Yatak Odası — 082",
    "categoryId": "bedroom",
    "collection": "Tokyo Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/tokyo-yatak-odasi-082.webp"
  },
  {
    "id": "AW-2027-083",
    "title": "Tokyo Yatak Odası — 083",
    "categoryId": "bedroom",
    "collection": "Tokyo Yatak Odası",
    "imageUrl": "/catalog/2027/bedroom/tokyo-yatak-odasi-083.webp"
  },
  {
    "id": "AW-2027-084",
    "title": "Tokyo Yemek Odası — 084",
    "categoryId": "dining",
    "collection": "Tokyo Yemek Odası",
    "imageUrl": "/catalog/2027/dining/tokyo-yemek-odasi-084.webp"
  },
  {
    "id": "AW-2027-085",
    "title": "Tokyo Yemek Odası — 085",
    "categoryId": "dining",
    "collection": "Tokyo Yemek Odası",
    "imageUrl": "/catalog/2027/dining/tokyo-yemek-odasi-085.webp"
  },
  {
    "id": "AW-2027-086",
    "title": "Tokyo Yemek Odası — 086",
    "categoryId": "dining",
    "collection": "Tokyo Yemek Odası",
    "imageUrl": "/catalog/2027/dining/tokyo-yemek-odasi-086.webp"
  },
  {
    "id": "AW-2027-087",
    "title": "Tokyo Yemek Odası — 087",
    "categoryId": "dining",
    "collection": "Tokyo Yemek Odası",
    "imageUrl": "/catalog/2027/dining/tokyo-yemek-odasi-087.webp"
  }
];
