/**
 * Import desktop ASİL furniture photos → public/catalog/2027 as high-quality WebP
 * and generate lib/catalog.generated.ts
 *
 * Run: node scripts/import-catalog.mjs
 */
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

const SOURCE_ROOT = String.raw`c:\Users\ASUS\OneDrive\Masaüstü\ASİL`;
const OUT_ROOT = path.join(process.cwd(), "public", "catalog", "2027");
const GENERATED = path.join(process.cwd(), "lib", "catalog.generated.ts");

const MAX_EDGE = 2000;
const WEBP_QUALITY = 86;

/** @typedef {{ category: string, collection?: string, src: string, outName: string, title: string }} Job */

function slugify(input) {
  return input
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/ı/g, "i")
    .replace(/İ/g, "i")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 48);
}

function baseKey(filename) {
  return filename
    .replace(/\.(jpe?g|png|webp|tif{1,2})$/i, "")
    .replace(/\s*kopya(\s*\(\d+\))?$/i, "")
    .replace(/\s*-\s*Kopya(\s*\(\d+\))?$/i, "")
    .replace(/_1$/i, "")
    .trim()
    .toLowerCase();
}

function isImage(file) {
  return /\.(jpe?g|png|webp|tif{1,2})$/i.test(file);
}

function preferUnique(files) {
  /** @type {Map<string, string>} */
  const map = new Map();
  for (const file of files) {
    if (!isImage(file)) continue;
    const key = baseKey(path.basename(file));
    const name = path.basename(file);
    const existing = map.get(key);
    if (!existing) {
      map.set(key, file);
      continue;
    }
    const existingIsCopy = /kopya/i.test(path.basename(existing));
    const currentIsCopy = /kopya/i.test(name);
    if (existingIsCopy && !currentIsCopy) map.set(key, file);
  }
  return [...map.values()];
}

function listFilesRecursive(dir) {
  /** @type {string[]} */
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listFilesRecursive(full));
    else if (entry.isFile() && entry.name.toLowerCase() !== "thumbs.db") {
      out.push(full);
    }
  }
  return out;
}

/** @returns {Job[]} */
function collectJobs() {
  /** @type {Job[]} */
  const jobs = [];
  let counter = 1;

  const pushFiles = (files, category, collection, titlePrefix) => {
    for (const src of preferUnique(files)) {
      const idNum = String(counter++).padStart(3, "0");
      const outName = `${slugify(collection || category)}-${idNum}.webp`;
      const title = collection
        ? `${collection} — ${idNum}`
        : `${titlePrefix} ${idNum}`;
      jobs.push({ category, collection, src, outName, title });
    }
  };

  // Salon / oturma
  pushFiles(
    listFilesRecursive(path.join(SOURCE_ROOT, "koltuk")),
    "living",
    "Salon & Oturma",
    "Oturma",
  );

  // Lamia line
  pushFiles(
    listFilesRecursive(path.join(SOURCE_ROOT, "Lamia 2023 jpg (5000 px)")),
    "lamia",
    "Lamia",
    "Lamia",
  );

  // Yatak baza / karyola
  pushFiles(
    listFilesRecursive(path.join(SOURCE_ROOT, "Yatak")),
    "bedset",
    "Yatak & Baza",
    "Yatak",
  );

  // Named bedroom / dining sets
  const bedroomRoot = path.join(SOURCE_ROOT, "yatak odası");
  if (fs.existsSync(bedroomRoot)) {
    for (const entry of fs.readdirSync(bedroomRoot, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const full = path.join(bedroomRoot, entry.name);
      const name = entry.name;
      if (/yemek/i.test(name)) {
        pushFiles(listFilesRecursive(full), "dining", name, "Yemek");
      } else if (/yatak/i.test(name)) {
        pushFiles(listFilesRecursive(full), "bedroom", name, "Yatak Odası");
      }
    }
  }

  return jobs;
}

async function convertJob(job) {
  const dir = path.join(OUT_ROOT, job.category);
  fs.mkdirSync(dir, { recursive: true });
  const dest = path.join(dir, job.outName);
  await sharp(job.src)
    .rotate()
    .resize({
      width: MAX_EDGE,
      height: MAX_EDGE,
      fit: "inside",
      withoutEnlargement: true,
    })
    .webp({ quality: WEBP_QUALITY, effort: 5 })
    .toFile(dest);
  return `/catalog/2027/${job.category}/${job.outName}`;
}

function emitTs(items) {
  const body = JSON.stringify(items, null, 2);
  const file = `/* Auto-generated by scripts/import-catalog.mjs — do not edit by hand */
export type CatalogCategoryId =
  | "living"
  | "bedroom"
  | "bedset"
  | "dining"
  | "lamia"
  | "others";

export type CatalogItem = {
  id: string;
  title: string;
  categoryId: CatalogCategoryId;
  collection: string | null;
  imageUrl: string;
};

export const catalogYear = 2027;

export const catalogItems: CatalogItem[] = ${body};
`;
  fs.writeFileSync(GENERATED, file, "utf8");
}

async function main() {
  console.log("Source:", SOURCE_ROOT);
  console.log("Out:", OUT_ROOT);

  if (fs.existsSync(OUT_ROOT)) {
    fs.rmSync(OUT_ROOT, { recursive: true, force: true });
  }
  fs.mkdirSync(OUT_ROOT, { recursive: true });

  const jobs = collectJobs();
  console.log(`Converting ${jobs.length} images…`);

  /** @type {import('./import-catalog.mjs') extends never ? never : any[]} */
  const items = [];

  for (let i = 0; i < jobs.length; i++) {
    const job = jobs[i];
    const imageUrl = await convertJob(job);
    const id = `AW-2027-${String(i + 1).padStart(3, "0")}`;
    items.push({
      id,
      title: job.title,
      categoryId: job.category,
      collection: job.collection ?? null,
      imageUrl,
    });
    if ((i + 1) % 10 === 0 || i === jobs.length - 1) {
      console.log(`  ${i + 1}/${jobs.length}`);
    }
  }

  emitTs(items);
  console.log(`Wrote ${items.length} items → ${GENERATED}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
